# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180202_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
